### ISSUE TITLE
HAProxy stats page port

### ISSUE THREAD

**Issue by jim256** [u1234x1234/torpool#1]
This is probably a really dumb question, but at what port can I view the HAProxy stats page?

**Comment by u1234x1234** [comment]
Thank you for your interest.

To view HAProxy stats page:
```
docker run -d -p 9200:9200 -p 9300:9300 -p 9500:9500 u1234x1234/torpool:1.0.2
```
Then open in browser http://localhost:9500/haproxy_stats and enter HAProxy username and password. The default username is `haproxy`, password is `password`, but it can be changed using using the volume mounting:
```
echo "pss" > pass_file
docker run -d -p 9200:9200 -p 9300:9300 -p 9500:9500 -v "$PWD/pass_file":/run/secrets/haproxy_password u1234x1234/torpool:1.0.2
```
Expected password location: `/run/secrets/haproxy_password`, username: `/run/secrets/haproxy_username`.

**Comment by jim256** [comment]
Thanks so much for such a detailed / thorough answer, and for updating the ReadMe too. Definitely went above and beyond!

This is one of the only dockerized, HTTP proxy projects I could find that used Tor and HaProxy where the version of HaProxy wasn't extremely old. Thank you *so* much for this! Helping my project a lot :)
