### ISSUE TITLE
bitcoind cannot authenticate with tor, "tor: Requesting protocol info failed"

### ISSUE THREAD

**Issue by bcashlol** [u1234x1234/torpool#4]
When trying to use a Dockerized bitcoind to connect to tor, it works fine if I run a single tor instance in a simple docker container.

If I replace my tor docker container with torpool, then bitcoind reports error "tor: Requesting protocol info failed".

I have tried using tor password authentication instead, and disabling cookie authentication in tor running in the torpool container.

Has anyone used bitcoind with torpool, or another service that needs access to tor's controlport to function?

**Comment by u1234x1234** [comment]
Could you provide a minimal reproducible example (the command you used to start bitcoind and/or Dockerfile)? I haven't tried using bitcoind before.

**Comment by bcashlol** [comment]
Make a directory with 2 files. Dockerfile and bitcoin.conf.

Dockerfile:  
```
FROM alpine:3.12 
RUN apk update && apk add git \
                          make \
                          file \
                          autoconf \
                          automake \
                          build-base \
                          libtool \
                          db-c++ \
                          db-dev \
                          boost-system \
                          boost-program_options \
                          boost-filesystem \
                          boost-dev \
                          libressl-dev \
                          libevent-dev
RUN git clone https://github.com/bitcoin/bitcoin --branch 0.20 --single-branch
RUN (cd bitcoin && ./autogen.sh && \
                      ./configure \
                      --without-gui \
                      --with-incompatible-bdb && \
                      make -j 4 && make install )
CMD bitcoind
```

bitcoin.conf:  
```
server=1
proxy=127.0.0.1:9200
listen=1
bind=127.0.0.1
```



Now build (this will take ~15 minutes depending on your machine):
`docker build -t bitcoind .`

Now run:
`docker run -it --net="host" -v /home/<user>/.bitcoin:/root/.bitcoin --name bitcoind_run bitcoind`

bitcoind runs, and this creates ~/.bitcoin/ on your host. Now ctrl+c out of bitcoind and kill the container.

Now copy/overwrite our bitcoin.conf to .bitcoin on host:

`rm ~/.bitcoin/bitcoin.conf && cp bitcoin.conf ~/.bitcoin/`

Run your torpool container with host networking (`--net="host"`) using port 9200 for socks5 proxy.

Now run the container again:

`docker start -i bitcoind_run`

Let bitcoind start up and wait for it to try to connect to tor to see the error message.

**Comment by u1234x1234** [comment]
Thank you for the provided example.

`Run your torpool container with host networking (--net="host") using port 9200 for socks5 proxy.`
You will get the "tor: Requesting protocol info failed" error if you pass the "-net=host" option when starting `torpool`.
If you do not pass the "-net=host" option, this error disappears.

Here the log without "net=host" option:

[log.txt](https://github.com/u1234x1234/torpool/files/5212396/log.txt)

**Comment by bcashlol** [comment]
It still does not work for me.

Can you tell me the run command you use for bitcoind and for torpool?

I run torpool with:

`docker run -p 9200:9200 -p 9300:9300 --name=torpool_run torpool --Tors=5`

And bitcoind with:

```
docker run -it \
        --net container:torpool_run \
        -v /home/user/.bitcoin:/root/.bitcoin \
        --name bitcoind_run bitcoind
```

**Comment by u1234x1234** [comment]
```bash
docker build -t bitcoind .
docker run -d -p 9200:9200 -p 9300:9300 u1234x1234/torpool:1.0.2 --Tors=5
docker run -it --net="host" -v ~/.bitcoin:/root/.bitcoin --name bitcoind_run bitcoind
```

**Comment by bcashlol** [comment]
It works, thank you.
