### ISSUE TITLE
Any way to update the version of HAProxy being used?

### ISSUE THREAD

**Issue by jim256** [u1234x1234/torpool#5]
I noticed that the stats page shows 2.0.11, but I couldn't see where you were explicitly specifying a version anywhere.

Any way to update to either 2.2.13 or 2.3.9?

**Comment by u1234x1234** [comment]
Hi Jared, I've updated HAProxy to 2.3.9. Please check up 1.0.3 tag:
```bash
docker run -d -p 9200:9200 -p 9300:9300 -p 9500:9500 u1234x1234/torpool:1.0.3
```

**Comment by jim256** [comment]
Awesome! Thank you so much
